### ISSUE TITLE
Testing: Site testing for MackTrucks BS (QA & UAT)

### ISSUE THREAD

**Issue by DanielaPedrochevd** [hlxsites/vg-macktrucks-bs#3]

**Comment by girishdigrajkar** [comment]
As confirmed with Manuel, Bahamas site is available for testing hence, marking this issue to Ready for testing

**Comment by girishdigrajkar** [comment]
Validated Bahamas site for HomePage and Find a Dealer.

**Comment by girishdigrajkar** [comment]
Testing is not fully completed
Issues logged so far :  https://github.com/hlxsites/vg-macktrucks-bs/issues/13

**Comment by shirin27** [comment]
As discussed with Becky, the testing tickets are out of scope for the Netcentric team and will be assigned to CMS team.
